version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:latest
    container_name: prisism-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
    volumes:
      - prisism-postgres:/var/lib/postgresql/data
    extra_hosts:
      - "host.containers.internal:host-gateway"

  server:
    image: prisism/prisism-server:latest
    container_name: prisism-server
    ports:
      - "3030:3030"
      - "3001:3001"
    env_file:
      - .env

  certbot:
    image: certbot/certbot
    container_name: prisism-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx
    container_name: prisism-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api.prisism.com:/etc/nginx/sites-available/api.prisism.com
      - ./nginx/proxy_params:/etc/nginx/proxy_params
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

volumes:
  prisism-postgres:
